from app.crud.base import CRUDBase
from app.models.account_health_declarations import AccountHealthDeclaration
from app.schemas.account_health_declarations import AccountHealthDeclarationCreate, AccountHealthDeclarationUpdate

account_health_declaration_crud = CRUDBase[
    AccountHealthDeclaration, AccountHealthDeclarationCreate, AccountHealthDeclarationUpdate
](AccountHealthDeclaration)
