-- =============================================================================
-- All 73 application tables, grouped by business area, one SELECT * per table.
-- Generated by scanning db/tables/*.sql (CREATE TABLE statements); table
-- order within each group follows the numeric file order they're defined in.
-- Purely a read reference for exploring the schema/data — not part of the
-- migration chain (db/run_all.sql), safe to run any subset standalone.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Reference Data / Org Structure  (db/tables/01_reference_data.sql)
-- -----------------------------------------------------------------------------
SELECT * FROM organizations;
SELECT * FROM geos;
SELECT * FROM regions;
SELECT * FROM project_types;
SELECT * FROM products;
SELECT * FROM accounts;
SELECT * FROM reporting_periods;


-- -----------------------------------------------------------------------------
-- 2. Users, Roles & Access  (02_users_roles.sql, 33_user_scope_assignments.sql)
-- -----------------------------------------------------------------------------
SELECT * FROM roles;
SELECT * FROM users;
SELECT * FROM user_geos;
SELECT * FROM user_accounts;
SELECT * FROM user_projects;


-- -----------------------------------------------------------------------------
-- 3. Projects — Core  (03_projects.sql, 32_project_documents.sql)
-- -----------------------------------------------------------------------------
SELECT * FROM projects;
SELECT * FROM project_oracle_ids;
SELECT * FROM project_resources;
SELECT * FROM project_documents;


-- -----------------------------------------------------------------------------
-- 4. Project Creation & Amendments  (48-50)
-- -----------------------------------------------------------------------------
SELECT * FROM project_creation_requests;
SELECT * FROM project_creation_request_oracle_ids;
SELECT * FROM project_amendments;
SELECT * FROM project_amendment_snapshots;


-- -----------------------------------------------------------------------------
-- 5. Health Declarations & RAG Status  (04, 37, 38, 41)
-- -----------------------------------------------------------------------------
SELECT * FROM health_declarations;
SELECT * FROM account_health_declarations;
SELECT * FROM geo_health_declarations;
SELECT * FROM project_health_items;
SELECT * FROM account_health_items;


-- -----------------------------------------------------------------------------
-- 6. Status Reporting — Project / Account / Geo  (05, 34-36, 52)
-- -----------------------------------------------------------------------------
SELECT * FROM project_status_reports;
SELECT * FROM account_status_reports;
SELECT * FROM geo_status_reports;
SELECT * FROM project_status_items;
SELECT * FROM account_status_items;
SELECT * FROM geo_status_items;
SELECT * FROM monthly_report_attestations;


-- -----------------------------------------------------------------------------
-- 7. RAIDO Register  (06-10)
-- -----------------------------------------------------------------------------
SELECT * FROM risk_log;
SELECT * FROM issue_log;
SELECT * FROM dependency_log;
SELECT * FROM assumption_log;
SELECT * FROM opportunity_log;


-- -----------------------------------------------------------------------------
-- 8. Measurement — Delivery Metrics  (11-16, 45)
-- -----------------------------------------------------------------------------
SELECT * FROM measurement_development;
SELECT * FROM measurement_development_defects;
SELECT * FROM measurement_support;
SELECT * FROM measurement_staffing;
SELECT * FROM measurement_staffing_priority_metrics;
SELECT * FROM measurement_testing;
SELECT * FROM measurement_cloud_maintenance;
SELECT * FROM measurement_cloud_migration;
SELECT * FROM measurement_consulting;


-- -----------------------------------------------------------------------------
-- 9. Metric Targets  (24-29, 46)
-- -----------------------------------------------------------------------------
SELECT * FROM metric_target_development;
SELECT * FROM metric_target_support;
SELECT * FROM metric_target_staffing;
SELECT * FROM metric_target_staffing_priority;
SELECT * FROM metric_target_testing;
SELECT * FROM metric_target_cloud_maintenance;
SELECT * FROM metric_target_cloud_migration;
SELECT * FROM metric_target_consulting;


-- -----------------------------------------------------------------------------
-- 10. Contractual Compliance  (17-18)
-- -----------------------------------------------------------------------------
SELECT * FROM contractual_commitments;
SELECT * FROM contractual_commitment_actuals;
SELECT * FROM milestone_payments;
SELECT * FROM milestone_payment_actuals;


-- -----------------------------------------------------------------------------
-- 11. Delivery Excellence (DE) Assessment  (19-20, 47)
-- -----------------------------------------------------------------------------
SELECT * FROM de_assessments;
SELECT * FROM de_assessment_findings;
SELECT * FROM de_assessment_finding_history;
SELECT * FROM de_project_module_reviews;
SELECT * FROM data_integrity_checklist_items;


-- -----------------------------------------------------------------------------
-- 12. Action Tracker  (44)
-- -----------------------------------------------------------------------------
SELECT * FROM actions;
SELECT * FROM action_history;


-- -----------------------------------------------------------------------------
-- 13. Executive Updates  (43)
-- -----------------------------------------------------------------------------
SELECT * FROM executive_updates;


-- -----------------------------------------------------------------------------
-- 14. Notifications  (51)
-- -----------------------------------------------------------------------------
SELECT * FROM notifications;


-- -----------------------------------------------------------------------------
-- 15. AI Suggestions  (30-31)
-- -----------------------------------------------------------------------------
SELECT * FROM ai_field_suggestions;
SELECT * FROM ai_row_suggestions;


-- -----------------------------------------------------------------------------
-- 16. Integrations & Ops/Audit  (21-23)
-- -----------------------------------------------------------------------------
SELECT * FROM integration_connections;
SELECT * FROM backup_restore_log;
SELECT * FROM user_activity_log;
SELECT * FROM id_sequences;
